openapi: 3.0.0
info:
  title: Documentación de las APIs
  version: 1.0.0
  description: Información de la integración de Users, Products, Cart
  contact:
    name: Carlos Barrera
    url: 
servers:
  - url: http://localhost:8080
    description: Servidor Local
paths:
  /api/users/register:
    post:
      summary: Registrar un nuevo usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
                email:
                  type: string
                age:
                  type: number
                dni:
                  type: number
                gender:
                  type: string
                birthDate:
                  type: number
                password:
                  type: string
      responses:
        "201":
          description: Usuario registrado exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: Usuario registrado exitosamente
                  payload:
                    type: object
                    properties:
                      first_name:
                        type: string
                      last_name:
                        type: string
                      email:
                        type: string
                      age:
                        type: number
                      dni:
                        type: number
                      gender:
                        type: string
                      birthDate:
                        type: number
                      role:
                        type: string
  /api/users/:
    get:
      summary: Obtener todos los usuarios
      responses:
        "200":
          description: Lista de todos los usuarios registrados
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  payload:
                    type: array
                    items:
                      type: object
                      properties:
                        first_name:
                          type: string
                        last_name:
                          type: string
                        email:
                          type: string
                        age:
                          type: number
                        dni:
                          type: number
                        gender:
                          type: string
                        birthDate:
                          type: number
                        role:
                          type: string
    put:
      summary: Cambiar rol de usuario
      parameters:
        - in: path
          name: uid
          required: true
          schema:
            type: string
          description: El ID del usuario cuyo rol necesita ser cambiado.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                newRole:
                  type: string
                  enum: [user, admin, premium]
      responses:
        "200":
          description: El rol del usuario cambió exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: El rol del usuario cambió exitosamente
                  payload:
                    type: object
                    properties:
                      first_name:
                        type: string
                      last_name:
                        type: string
                      email:
                        type: string
                      age:
                        type: number
                      dni:
                        type: number
                      gender:
                        type: string
                      birthDate:
                        type: number
                      role:
                        type: string
  /api/auth/recover:
    post:
      summary: Recuperar contraseña
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
      responses:
        "200":
          description: Correo electrónico de recuperación enviado correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: Correo electrónico de recuperación enviado correctamente
  /api/reset/{token}:
    get:
      summary: Restablecer token de contraseña
      parameters:
        - in: path
          name: token
          required: true
          schema:
            type: string
          description: El token de restablecimiento de contraseña recibido en el correo electrónico de recuperación
    put:
      summary: Actualiza contraseña
      parameters:
        - in: path
          name: token
          required: true
          schema:
            type: string
          description: El token de restablecimiento de contraseña recibido en el correo electrónico de recuperación
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
      responses:
        "200":
          description: Contraseña actualizada exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: Contraseña actualizada exitosamente
