openapi: 3.0.0
info:
  title: Documentación de las APIs
  version: 1.0.0
  description: Información de la integración de Users, Products, Cart
  contact:
    name: Carlos Barrera
    url: 
servers:
  - url: http://localhost:8080
    description: Servidor Local
paths:
  /api/products/:
    get:
      summary: Obtener todos los productos
      responses:
        "200":
          description: Lista de productos
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  payload:
                    type: array
                    items:
                      type: object
                      properties:
                        _id:
                          type: string
                        title:
                          type: string
                        description:
                          type: string
                        price:
                          type: number
                        owner:
                          type: string
    post:
      summary: Crear un nuevo producto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: El título del producto.
                description:
                  type: string
                  description: La descripción del producto.
                price:
                  type: number
                  description: El precio del producto.
                owner:
                  type: string
                  description: El ID del propietario del producto (usuario)
      responses:
        "201":
          description: Producto creado exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: Producto creado exitosamente
                  payload:
                    type: object
                    properties:
                      _id:
                        type: string
                      title:
                        type: string
                      description:
                        type: string
                      price:
                        type: number
                      owner:
                        type: string
  /api/products/{productId}:
    get:
      summary: Obtener producto por ID
      parameters:
        - in: path
          name: productId
          schema:
            type: string
          required: true
          description: El ID del producto a recuperar.
      responses:
        "200":
          description: Producto recuperado exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  payload:
                    type: object
                    properties:
                      _id:
                        type: string
                      title:
                        type: string
                      description:
                        type: string
                      price:
                        type: number
                      owner:
                        type: string
        "404":
          description: Producto no encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  message:
                    type: string
                    example: Producto no encontrado
    put:
      summary: Actualizar producto por ID
      parameters:
        - in: path
          name: productId
          schema:
            type: string
          required: true
          description: El ID del producto a actualizar.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: El título actualizado del producto.
                description:
                  type: string
                  description: La descripción actualizada del producto.
                price:
                  type: number
                  description: El precio actualizado del producto.
      responses:
        "200":
          description: Producto actualizado exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: Producto actualizado exitosamente
                  payload:
                    type: object
                    properties:
                      _id:
                        type: string
                      title:
                        type: string
                      description:
                        type: string
                      price:
                        type: number
                      owner:
                        type: string
    delete:
      summary: Eliminar producto por ID
      parameters:
        - in: path
          name: productId
          schema:
            type: string
          required: true
          description: El ID del producto a eliminar.
      responses:
        "200":
          description: Producto eliminado exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: Producto eliminado exitosamente
        "404":
          description: Producto no encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  message:
                    type: string
                    example: Producto no encontrado
