openapi: 3.0.0
info:
  title: Documentaci칩n de las APIs
  version: 1.0.0
  description: Informaci칩n de la integraci칩n de Users, Products, Cart
  contact:
    name: Carlos Barrera
    url: 
servers:
  - url: http://localhost:8080
    description: Servidor Local
paths:
  /api/cart/:
    get:
      summary: Obtener todos los productos en el carrito
      responses:
        "200":
          description: Listado de productos en el carrito del usuario
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  payload:
                    type: array
                    items:
                      type: object
                      properties:
                        _id:
                          type: string
                        title:
                          type: string
                        description:
                          type: string
                        price:
                          type: number
    post:
      summary: Agregar producto al carrito
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                productId:
                  type: string
                  description: El ID del producto a agregar al carrito.
                userId:
                  type: string
                  description: El ID del usuario que agrega el producto al carrito.
      responses:
        "200":
          description: Producto agregado al carrito exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: Producto agregado al carrito exitosamente
                  payload:
                    type: object
                    properties:
                      _id:
                        type: string
                      userId:
                        type: string
                      products:
                        type: array
                        items:
                          type: object
                          properties:
                            _id:
                              type: string
                            title:
                              type: string
                            description:
                              type: string
                            price:
                              type: number
  /api/cart/addToCart:
    post:
      summary: Endpoint obsoleto
      deprecated: true
      responses:
        "405":
          description: Este endpoint est치 obsoleto; utilice POST /api/cart en su lugar
